version: '3'
services:
  atm_emulator:
    container_name: atm_emulator
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./prj:/prj
  bankservice:
    container_name: bankservice
    hostname: bankservice
    build:
      context: ./bankservice/
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    depends_on:
      - atm_emulator
  atmservice:
    container_name: atmservice
    hostname: atmservice
    build:
      context: ./atmservice
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - bankservice
    restart: always
